// <auto-generated />
namespace JobTracker.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class HackTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(HackTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201604160407256_HackTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
